### ISSUE TITLE
Is thare an official docker image for this project?

### ISSUE THREAD

**Issue by linuxd3v** [skavanagh/KeyBox#314]
Is there an official docker image in dockerhub?

**Comment by lucapalano** [comment]
No, there is no official docker image on dockerhub.

**Comment by davidwindell** [comment]
Please can we have one :)

**Comment by elRadix** [comment]
Any community docker edition ?

**Comment by stroskler** [comment]
This could be used to run bastillion on a `arm64` . But easily could be adjusted to `amd64` systems.

The config file can be found [here](https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties)

adjusted values:
* SSH Keys `/root/.ssh/id_rsa` and `/root/.ssh/id_rsa.pub`
* Passphrase (if set)
* DB Password

## Dockerfile
```
FROM arm64v8/ubuntu:22.04

RUN apt update && apt dist-upgrade -y &&\
    apt install -y \
    ca-certificates-java \
    wget \
    git

RUN apt install -y \
    openjdk-18-jre-headless \
    openjdk-18-jdk \
    maven

RUN git clone https://github.com/bastillion-io/Bastillion.git

WORKDIR Bastillion

COPY BastillionConfig.properties src/main/resources/

RUN mvn install

EXPOSE 8443
ENTRYPOINT ["mvn", "jetty:run"]
```
## Build the image
```
docker build -t bastillion-ubuntu .
```
## Use compose for persistence

```
version: '3'
services:
  bastillion:
    image: bastillion-ubuntu
    ports:
      - 8443:8443
    volumes:
      - ./data:/Bastillion/target
```
